# -*- coding: utf-8 -*-
"""MachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4jaYloRDAhNP3jUCB7owOiSEyEa0sYX
"""

from sklearn.datasets import load_iris
iris=load_iris()

print(iris.keys())

print(iris['DESCR'])

print(iris['target_names'])

print(iris['feature_names'])

print(type(iris['data']))

print(iris['data'].shape)

print(iris['data'][:5])

print(iris['target'])

from sklearn.model_selection import train_test_split
X_egitim, X_test, y_egitim, y_test = train_test_split(iris['data'], iris['target'], random_state=0)

print(X_egitim.shape)
print(y_egitim.shape)

print(X_test.shape)
print(y_test.shape)

import pandas as pd

iris_df=pd.DataFrame(X_egitim, columns=iris.feature_names)

from pandas.plotting import scatter_matrix

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

scatter_matrix(iris_df, c=y_egitim, figsize=(15,15), marker='o', hist_kwds={'bins':20}, s=80, alpha=0.8)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

knn.fit(X_egitim, y_egitim)

import numpy as np
X_yeni=np.array([[5,2.9,1,0.2]])
X_yeni.shape

tahmin = knn.predict(X_yeni)
print('Tahmin sınıfı: ',tahmin)
print('Tahmin türü:', iris['target_names'][tahmin])

y_tahmin=knn.predict(X_test)
print(y_tahmin)

print(np.mean(y_tahmin==y_test))

print(knn.score(X_test,y_test))

